### PR TITLE
Some improvements/fixes

### PR DESCRIPTION
**Pull request by mgeorgiou**
Here are some minor improvements/fixes for your website.
- Open pdfs in new tabs
- Remove unused url refs from the titles below the name
- Remove annoying background image that is hunting your page (see screenshot)

Screenshot 2019-10-25 at 00 02 09

### CODE REVIEW

**Comment by Nikronic** [comment]
Thank you so much it is great!

**Comment by mgeorgiou** [comment]
Your website is nice and your achievements outstanding. Keep up the good work buddy 👍

**Comment by Nikronic** [comment]
The website is a template in fact and I know nothing about web :-)! But thank you for the other part. I wish you best mate.
Actually, I am trying to apply and study in Europe, and currently I am stuck in acquiring IELTS!

**Comment by pablostellet** [comment]
yeah, I agree with @mgeorgiou 
You have a lot of potential. I am cheering for you ;)

**Comment by Nikronic** [comment]
@pablostellet I am really appreciated, you are so kind. I sincerely wish you bests.

**Pull request merged**
